"use strict";
var express = require('express');
var path = require('path');
var stylus = require('stylus');
var routes = require('./routes/index');
var user_routes = require('./routes/user');
var mongoose = require('mongoose');
var config = require('./config');
var logger = require('express-logger');
var errorHandler = require('express-errorhandler');
var http = require('http');
var app = express();
var server = http.createServer(app);
var printLogger = require('./middlewares/logRequest');
var pug = require('pug');
var bodyParser = require('body-parser');
app.set('port', config.PORT);
app.set('view engine', 'pug');
app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, 'public')));
app.use(stylus.middleware(path.join(__dirname, 'public')));
app.use(logger({ path: path.join(__dirname, 'logs.txt') }));
app.use(printLogger);
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
mongoose.connect(config.db_dev);
app.get('/', routes.index);
app.get('/create_user', user_routes.create_user);
app.post('/create_user', user_routes.create_user);
server.listen(app.get('port'), function () {
    console.log('Express server is listening on port ' + app.get('port'));
});
